config/routes.rb
OssDb::Application.routes.draw do
  root :to => 'admin#home'
  match '/logout' => 'application#logout', :as => :logout
  match '/version' => 'version#show', :as => :version
  match '/plan_of_execution/process/:id' => 'plan_of_execution#process_poe'

  resource :report, :only => [:index] do
    get :index    
    get :sla
    get :oem_sla
    get :circuit_utilization
    get :enni_utilization
  end
  
  resources :ennis
  resources :ports
  resources :nodes

  match '/plan_of_execution(/:action(/:id(/:version)))' => "plan_of_execution"

  match '/:controller(/:action(/:id))'
end

app/models/site.rb
# == Schema Information
#
# Table name: sites
#
#  id                     :integer(4)      not null, primary key
#  name                   :string(255)
#  address                :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  contact_info           :string(255)
#  site_host              :string(255)
#  floor                  :string(255)
#  clli                   :string(255)
#  icsc                   :string(255)
#  network_address        :string(255)
#  broadcast_address      :string(255)
#  host_range             :string(255)
#  hosts_per_subnet       :string(255)
#  notes                  :text
#  node_prefix            :string(255)
#  postal_zip_code        :string(255)
#  emergency_contact_info :string(255)
#  site_access_notes      :text
#  city                   :string(255)
#  state_province         :string(255)
#  site_type              :string(255)
#  latitude               :decimal(9, 6)   default(0.0)
#  longitude              :decimal(9, 6)   default(0.0)
#  type                   :string(255)
#  operator_network_id    :integer(4)
#  country                :string(255)
#  service_id_low         :integer(4)
#  service_id_high        :integer(4)
#  site_layout            :string(255)     default("StandardExchange7750")
#

class Site < ActiveRecord::Base
  include Kpiable
  
  has_many :site_groups_sites
  has_many :site_groups, :through => :site_groups_sites

  has_many :nodes, :order => "name", :dependent => :destroy
  has_many :inventory_items, :dependent => :destroy
  has_many :patch_panels, :order => "name", :dependent => :destroy
  has_many :cabinets, :order => "name", :dependent => :destroy
  has_many :ports, :through => :nodes, :order => "name"
  has_many :uploaded_files, :as => :uploader, :dependent => :destroy
  belongs_to :operator_network
  has_one :service_provider, :through => :operator_network
    
  has_many :demarcs, :dependent => :destroy
  has_many :ennis, :class_name => 'EnniNew'
  has_many :on_net_ovcs, :class_name => 'OnNetOvc', :dependent => :nullify
  has_many :qos_policies, :dependent => :destroy
  has_many :enni_news, :class_name => 'EnniNew'
  has_many :segments

  validates_presence_of :name, :country, :city, :node_prefix, :site_host, :address, :contact_info, :floor, :network_address, :broadcast_address, :host_range, :hosts_per_subnet, :site_type, :operator_network_id
  validates_uniqueness_of :name
  validates_uniqueness_of :network_address, :unless => Proc.new { |site| site.network_address == "TBD" }
  validates_format_of :network_address, :with => /(^$)|(^(\d{1,3}\.){3}(\d{1,3})(\/\d{1,2})$)/, :message => "Should be format a.b.c.d/e", :unless => Proc.new { |site| site.network_address == "TBD" }
  validates_uniqueness_of :broadcast_address, :unless => Proc.new { |site| site.broadcast_address == "TBD" }
  validates_format_of :broadcast_address, :with => /(^$)|(^(\d{1,3}\.){3}(\d{1,3})$)/, :message => "Should be dotted decimal IP", :unless => Proc.new { |site| site.broadcast_address == "TBD" }
  validates_format_of :loopback_address, :with => /(^$)|(^(\d{1,3}\.){3}(\d{1,3})$)/, :message => "Should be dotted decimal IP"
  validates_uniqueness_of :host_range, :unless => Proc.new { |site| site.host_range == "TBD" }
  validates_inclusion_of :site_layout, :in => HwTypes::SITE_LAYOUTS, :message => "invalid, Use: #{HwTypes::SITE_LAYOUTS.join(", ")}"
  
  validate :site_layout_valid?
  validate :valid_site_type?
  validate :valid_operator_network?  
  
  MINI_SITE_LAYOUTS = ["LightSquaredExchange7210_SGW"]
  
  # Determine type of Site based on the site layout
  # TODO: Probably should be attribute instead of regex
  def general_type
    case site_layout
    when /wdc/i
      'wdc'
    when /cdc/i
      'gateway_site'
    when /msc/i
      'agg_site'
    else
      'agg_site'
    end
  end
  
  def enni_count
    return demarcs.size #TODO only count demarks that are ENNIs
  end

  # TODO: I think site.path_count is obsolete now?
  def path_count
    # LESS EFFICIENT: on_net_ovcs.map{|onovc| onovc.paths.map(&:id)}.flatten.uniq.count
    on_net_ovcs.joins(:paths).count(:path_id, :distinct => true)
  end

  # Path counts need to restricted by operator network type
  def path_count_by_operator_network_type(operator_network_types)
    # use diagrams to determine Paths by operator network
    path_count = if operator_network_types.empty?
      ennis.joins(:path_displays)
    else
      ennis.joins(:path_displays => {:path => :operator_network}).where(:operator_networks => {:operator_network_type_id => operator_network_types})
    end
    path_count = path_count.count(:path_id, :distinct => true)
  end

  def cenx_mon_ennis_count
    return demarcs.select{ |d| d.is_connected_to_monitoring_port}.size
  end

  def member_ennis_count
    return demarcs.reject{ |d| d.is_connected_to_monitoring_port}.size
  end

  def on_ovc_count
    return on_net_ovcs.size
  end
  
  def self.find_rows_for_index
    order("name")
  end
  

  def site_configuration

    switch_nodes = []
    nodes.each do |node|
      if (node.is_service_router)
        switch_nodes << node
      end
    end
    
    mon_nodes = []
    nodes.each do |node|
      if (node.is_monitoring_node)
        mon_nodes << node
      end
    end

    one_or_ten = "One"
    
    switch_nodes.each do |node|
      node.ports.each do |port|
        if port.phy_type.include? "10GigE"
          one_or_ten = "Ten"
          break
        end
      end
    end

    #TODO fix DUALN vs DUALP
    return "#{switch_nodes.size > 1 ? "DUALP" : "SINGLE"} #{one_or_ten} #{mon_nodes.size > 0 ? "MON" : "NOT-MON"}"
  end
  
  def is_mini_site?
    return MINI_SITE_LAYOUTS.include? site_layout
  end


  def get_seed_module
    #This function gets the site layout, removes spaces
    # and gets the module of the same type
    type = site_layout.gsub(/ +/, "")
    mod = Kernel.const_get(type)
    return mod
  end

  def site_types
    #returns the possible sites of the seed module
    mod = get_seed_module
    return mod::SITES.keys
  end

  def possible_site_types
    possible = site_types.dup
    possible.delete(site_type)
    return possible
  end


  def site_group_info
    site_groups.collect {|sg| sg.name}.uniq.join(" ;")
  end

  def onovc_count
    return on_net_ovcs.size
  end
  
  def on_info_site
    return operator_network ? operator_network.name : "TBD"
  end
  
  def rename_nodes new_prefix
    return false unless Site.find_by_node_prefix(new_prefix).nil?

    nodes.each do |node|
      node.name = node.name.sub(node_prefix, new_prefix)
      node.save false
    end

    self.node_prefix = new_prefix
    self.save false
    return true
  end
  
  def get_setup
    seeds = get_seed_module
    setup = seeds::SITES[site_type]
    return setup
  end
  
  def can_seed
    setup = get_setup
    #Must have no nodes and have a seed defined for it
    return nodes.empty? && defined?(setup)
  end
  
  def seed
    setup = get_setup
    #Make sure all requirements are meant before seeding.
    unless nodes.empty?
      SW_ERR "EXL: Error #{name} can not seed, already has defined nodes"
      return nil
    end
    unless defined?(setup)
      SW_ERR "EXL: Error #{name} can not seed, #{site_type} seed not found/valid"
      return nil
    end
    unless defined?(setup::PORT_CONNECTIONS) && defined?(setup::NODE_INSTANCE)
      SW_ERR "EXL: Error #{name} can not seed, #{site_type} seed missing headers"
      return nil
    end
    
    seed_nodes
    connect_ports
    seed_ennis
  end
  
  def seed_nodes
    @node_seeds = Hash.new
    setup = get_setup
    #for each item in the seeds
    setup::NODE_INSTANCE.each{|name, node_instance|
      #create the associated node
      node = Node.new
      node.node_type = node_instance[:node][:type]
      node.site = self
      node.set_defaults node_instance
      info = node_instance[:node][:nm_connection]
      node.network_manager = NetworkManager.first(:conditions => ["name = ? and nm_type = ?", info[:name], info[:nm_type]]) unless info.nil?
      SW_ERR("Could not create Node: #{node.name} #{node.primary_ip} " + node.errors.full_messages.join(", ")) unless node.save
      node.seed_ports node_instance
      node.save
      node.reload
      #Store the node according to it's instance for easy retrieval later
      @node_seeds[node_instance] = node
    }
    nodes(true)
  end
  
  def connect_ports
    setup = get_setup
    setup::PORT_CONNECTIONS.each do |connection|
      port1 = port_from_array connection[0], connection[1]
      port2 = port_from_array connection[1], connection[0]

      SW_ERR("Could not find Port1: #{connection[0][1]} on #{(@node_seeds[connection[0][0]]).name}") unless port1
      SW_ERR("Could not find Port2: #{connection[1][1]} on #{(@node_seeds[connection[1][0]]).name}") unless port2

      #puts "******** Connect #{self.name}: #{port1.name} to #{port2.name}"

      port1.connected_port = port2
      port2.connected_port = port1
      SW_ERR("Could not save Port: #{port1.name} " + port1.errors.full_messages.join(", ")) unless port1.save
      SW_ERR("Could not save Port: #{port2.name} " + port2.errors.full_messages.join(", ")) unless port2.save
    end
  end

  def port_from_array array, connection
    #Get the actual node by it's instance from the array
    node = @node_seeds[array[0]]

    unless node
      SW_ERR ("Could not find Node for #{array} to connect to #{connection}")
      return nil
    end

    #Find the first port that matches the name in the array
    return node.ports.first(:conditions => ['name = ?', array[1]])
  end
  
  
  def seed_ennis
    setup = get_setup
    #for every node we've seeded
    @node_seeds.each do |instance, node|
      #If this node doesn't connect to an ENNI skip it
      next if instance[:enni_connections].nil?
      instance[:enni_connections].each do |connection|       
        #seperate the enni attrs from the connected ports
        attrs = connection.dup

app/views/admin/_index_filter_bulk_order.html.erb
<div id="bulk_order_list_field" >	
<%= render :partial => 'list_any_type', :object => @sos,
             :locals => {
				:legend => 'Cenx Bulk Orders',
				:fcn_tail => 'bo',
				:cols => %w{ Title order\ type cenx\ id action path\ info State},
                                :local_link => 'title',
                                :detail_link => nil,
				:attrs => %w{bulk_order_type cenx_id action},
				:details => %w{ordered_entity_info get_order_name},
				:enable_search => true} %>
</div>

app/views/admin/_input_site.html.erb
<div id="input_column_left">
<p>Site Groups:<br/>
	<%= f.select :site_group_ids, options_from_collection_for_select(SiteGroup.all, :id, :name, @site.site_groups.collect{|sg| sg.id}), {}, {:multiple => true, :cols => 60} %>
</p>

<p> *Type:<br/>
<% if @site.site_type.nil? or is_new %>
  <% prompt = @site.possible_site_types.empty? ? "No Valid Site Types" : "Select" %>
  <%= f.select :site_type, @site.possible_site_types, :prompt => prompt %>
<% else %>
  <%= f.text_field :site_type, :disabled => true %>
<% end %>
</p>
<p> Site Layout:<br/> <%= f.select :site_layout, HwTypes::SITE_LAYOUTS, :prompt => "Select" %> </p>
<% if(@site.operator_network_id == nil || is_new) %>
<p> *Network:<br/> <%= f.select :operator_network_id,
         options_from_collection_for_select(@ons, :id, :name, @site.operator_network_id ),
         :prompt => "Select"%> </p>
<% else %>
  <p>Network:<br/><%= text_field_tag "site_operator_network_id", @site.on_info_site, :size => 50, :disabled => true %>
  <%= link_to "--View", :action => 'edit_on', :id =>  @site.operator_network_id %></p>
<% end %>
<p> *Name:<br/> <%= f.text_field :name%> </p>
<p> *Site Host<br/> <%= f.text_field :site_host%> </p>
<p> *City:<br/> <%= f.text_field :city %> </p>
<p> State/Province:<br/> <%= f.text_field :state_province %> </p>
<label>*Street Address: </label><br/>
<%= f.text_area :address, :cols => 40, :rows => 3%><br/>
<p> Zip/Postal Code:<br/> <%= f.text_field :postal_zip_code%> </p>
<p> *Country:<br/> <%= f.text_field :country %> </p>
<p> *Floor:<br/> <%= f.text_field :floor%> </p>
<p> CLLI:<br/> <%= f.text_field :clli%> </p>
<p> ICSC:<br/> <%= f.text_field :icsc%> </p>
<p> 24x7 Support Info: </label><br/>
<%= f.text_area :emergency_contact_info, :cols => 40, :rows => 2%></p>
<p> *Escalation Contact Info: </label><br/>
<%= f.text_area :contact_info, :cols => 40, :rows => 6%></p>
</div>
<div id="input_column_right"><br/><br/><br/>
<p> *Node Name Prefix:<br/> <%= f.text_field :node_prefix, :readonly => !is_new%></p>
<p> *Network Address:<br/> <%= f.text_field :network_address%> </p>
<p> *Broadcast Address:<br/> <%= f.text_field :broadcast_address%> </p>
<p> *Loopback Address:<br/> <%= f.text_field :loopback_address%> </p>
<p> *Host Range:<br/> <%= f.text_field :host_range%> </p>
<p> *Hosts per subnet:<br/> <%= f.text_field :hosts_per_subnet%> </p>
<p>Latitude:<br/>
  <%= f.text_field :latitude, :size => 30 %></p>
<p>Longitude:<br/>
  <%= f.text_field :longitude, :size => 30 %></p>
<p>Hardware Configuration:<br/> <%= text_field_tag 'site_config',@site.site_configuration, :size => 30, :disabled => true %> </p>
<p> Site Access Notes (How to get into building etc..):<br/> <%= f.text_area :site_access_notes, :cols => 40, :rows => 10%></p>
<p> Notes (Cabinet Lock Combinations etc..):<br/> <%= f.text_area :notes, :cols => 40, :rows => 10%></p>

<%= render(:partial => 'options_subclass_site', :locals => {:f => f}) %>
</div>
    

app/views/admin/_results_alarm_check.html.erb
<fieldset>
  <legend> <strong> <%= legend %> </strong> </legend>


  <% if @result.empty? %>
    No Alarm Keys Found
  <%  else %>
    <% @result.each do |key| %>
        <p><span style="color: red;"><%= key %></span></p>
    <% end %>
<% end %>

</fieldset>

app/views/admin/_update_state_info.html.erb
<fieldset id="state_info">
<div style="color: red" ><%= flash[:state_error] -%></div>

<%= javascript_tag do %>

function check_live_sanity(id, confirm_msg)
{          		
 var url = '<%= url_for(:action => 'sh_check_live_sanity') %>/' + id;
 notice = ""
 new Ajax.Request(url, {
  asynchronous:false, evalScripts:true,
  method: 'get',
  parameters:'authenticity_token=' + encodeURIComponent("<%= form_authenticity_token %>"),
  onSuccess: function(transport) {
    notice = transport.responseText
  }
 });
 return confirm_msg + "\n" + notice
}
<% end %>

<legend><b>State information</b></legend>
<div id="input_column_left">
<% display_states.each do |stateful| %>
  <%= stateful.name %>:
  <%= text_field_tag 'state', stateful.get_state.name, :size => 20, :readonly => true %>
<% end %>

<% change_states.each do |stateful| %>
  <% stateful.get_state.valid_transitions.each do |possible_state| %>
    <% if !stateful.get_state.is_a?(possible_state) %>
      <br>
      <% if !possible_state.new.is_a?(ProvLive) %>
	    <%=  button_to_remote "Move to '#{possible_state.state_name}' State", :url => {:action => 'sh_new_state', :id => stateful.id, :new_state => "#{possible_state.to_s}", :display_states => display_states, :change_states => change_states}, :confirm => "#{stateful.to_specific(possible_state).pre_text(stateful)}\nAre you sure?", :update => "updateable_state_div" %>
	
	  <% else %>  
	    <%=  button_to_remote "Move to '#{possible_state.state_name}' State", :url => {:action => 'sh_new_state', :id => stateful.id, :new_state => "#{possible_state.to_s}", :display_states => display_states, :change_states => change_states}, :onclick => "return confirm(check_live_sanity(#{stateful.id}, \"#{stateful.to_specific(possible_state).pre_text(stateful)}\") + \"\\nAre you sure?\")", :update => "updateable_state_div" %>
	
	<% end %>
    <% end %>
  <% end %>
<% end %>
</div>

<!= # Hide the field if no text =>
<% if !display_states.all? {|stateful| stateful.get_state.class.post_text(stateful).empty?} %>
<div id="input_column_right">
  To Do in Current State:
  <%= text_area_tag 'post actions', display_states.collect {|stateful| stateful.get_state.class.post_text(stateful)}.join("\n"), :readonly => true, :size => "50x2"%>
</div>
<% end %>
</fieldset>

app/views/admin/choose_cost_est.html.erb
<h1>Class of Service Type Selection for <%= @est.name %></h1>

<%= error_messages_for 'est' %>
<fieldset>
  <legend>Add a Class of Service Type</legend>
  <%= form_tag :action => 'add_cost_est', :id => @est.id do %>
  <%= collection_select( :cost , :id, @costs,  :id, :name ,
    options ={:prompt => "Select Class of Service Type"},
                         :class =>"cost")%> <br /><br />

    <%= submit_tag "Add to Ethernet Service Type", :id => @est.id %>
  <% end %>
</fieldset>

<%= link_to "Edit #{@est.name}", :action => 'edit_est', :id => @est.id %><br />

app/views/admin/choose_segment_path.html.erb
<h1>Segment Selection for <%= @path.cenx_name %></h1>

<%= error_messages_for 'path' %>
<%= error_messages_for 'segment' %>
<span><img alt="spinner" id="spinner" src="/images/small-loading.gif" style="display:none"/></span>
	
<fieldset>
  <legend>Select a Segment</legend>
  <%= form_tag :action => 'link_segment_path', :id => @path.id do %>
    <label>Segment:</label><br/>
    <%= if @segments
      collection_select( :segment , :id, @segments,  :id, :cenx_name , 
                         options ={:prompt => "Select a Segment"},
                         :class =>"segment")

    end %> 
    <%= if @segment_class
      hidden_field_tag( :segment_class, @segment_class)
    end %> 
    <br/>
    <%= submit_tag "Attach to Path", :id => @path.id %>
  <% end %>
</fieldset>

<%= link_to "Edit #{@path.cenx_name}", :action => 'edit_path', :id => @path.id %><br />

app/views/admin/config_gen_demarc.html.erb
<h1>Recommended Config for <%= @demarc.cenx_name%></h1>

<p> Copy the commands below to CLI on nodes indicated:<br/>
<%= text_area_tag 'demarc_config',@config_text, :style => "width:100%;", :rows => 30, :wrap => "off", :readonly => true %></p>

<%= link_to "Edit #{@demarc.cenx_name}", :action => 'edit_demarc', :id => @demarc.id %><br />

app/views/admin/edit_ap.html.erb
<h1>Edit Access Permission</h1>

<%= error_messages_for 'access_permission' %>

<%= form_for :access_permission, :url => { :action => 'update_ap', :id => @access_permission.id } do |f| %>
  <fieldset>
    <legend>Enter Access Permission Details</legend>
    <%= render( :partial => 'input_ap', :object => @access_permission, :locals => {:f => f, :is_new => false}) %>
  </fieldset>
  <%= submit_tag 'Save', :class => 'submit' %>
<% end %>

app/views/admin/edit_ma.html.erb
<h1>Edit Attribute Definition</h1>

<%= error_messages_for 'ma' %>

<%= form_for :ma, :url => { :action => 'update_ma', :id => @ma.id} do |f| %>
  <fieldset>
    <legend>Details</legend>
    <%= render :partial => 'input_ma', :object => @ma, :locals => {:f => f, :id => @ma.affected_entity_id, :new => false} %>
  </fieldset>
  <%= submit_tag 'Update', :class => 'submit' %>
<% end %>

<%= render :partial => 'list_any_type', :object => @macs,
             :locals => {
               :legend => 'Member Attribute Controls',
				:fcn_tail => 'mac',
				:cols => %w{summary type order},
                :local_link => 'description',
                :detail_link => nil,
                :attrs => %w{action execution_order},
				:details => %w{}
				} %>

<%= button_to 'Add', :action => 'new_mac', :id => @ma.id %>

<% if @ma.affected_entity_id %>
  <%= link_to "Edit Afftected Entity #{@ma.ae_info_ma}", :action => "edit_#{@ae_type}", :id => @ma.affected_entity_id %><br />
<% end %>

app/views/admin/index_bulk_order.html.erb
<span><img alt="spinner" id="spinner" src="/images/small-loading.gif" style="display:none"/></span>
<%= form_tag :action => 'index_bulk_order' do %>

  <%= render( :partial=> 'select_sp',  :object => @on,
                      :locals => {
                          :prompt => 'Filter by Member:',
                          :action => 'filter_sp_so',
                          :update => 'bulk_order_list_field',
                          :with => "'spid=' + value + '&tail=bulk'" }) %>

  <%= render( :partial=> 'index_filter_bulk_order' ) %>


  <%= submit_tag "Reset Filtering" %>
<% end %>

<%=  button_to 'New Order', {:action => 'new_bo'} %>

app/views/admin/index_costv.html.erb
<span><img alt="spinner" id="spinner" src="/images/small-loading.gif" style="display:none"/></span>
<%= form_tag :action => 'index_ii' do %>

  <%= render :partial => 'list_any_type', :object => @costvs,
             :locals => {
				:legend => 'Cos Test Vectors',
				:fcn_tail => 'costv',
				:cols => %w{Name Type Delay\ (Err) Delay\ (Warn) DV\ (Err) DV\ (Warn) FLR\ (Err) FLR\ (Warn) target},
                                :local_link => nil,
                                :detail_link => 'cenx_name',
				:attrs => %w{type delay_error_threshold delay_warning_threshold dv_error_threshold dv_warning_threshold flr_error_threshold flr_warning_threshold},
				:details => %w{test_target_address}
				} %>
<% end %>

app/views/admin/index_qosp.html.erb
<%= render :partial => 'list_any_type', :object => @qosps,
             :locals => {
				:legend => "QoS Policies",
				:fcn_tail => 'qosp',
				:cols => %w{Policy\ Name Policy\ ID Direction Site Nodes\ Involved Associated\ Endpoints},
                                :local_link => 'policy_name',
                                :detail_link => nil,
				:attrs => %w{policy_id},
				:details => %w{direction site_name node_info associated_endpoints_count},
                                :enable_search => true
				} %>

app/views/admin/new_bo.html.erb
<h1>Bulk Order</h1>
<%= error_messages_for 'so' %>
<%= form_for :so, :url => { :action => 'save_bo', :id => @on.id } do |f| %>
  <fieldset>
    <legend>Bulk Order Details</legend>
    <%= render(:partial => 'input_bo', :object => @so, :locals => {:f => f, :is_new => true}) %>
  </fieldset>
  <%= render(:partial => "options_instance_element", :locals => {:ie => @so, :tail => "so", :with => "" }) %>
  <%= submit_tag "Continue", :class => "submit" %>
<% end %>

<%= link_to "ENNI Inventory", :action => 'index_member_enni'%><br />
<%= link_to "On Net OVC Inventory", :action => 'index_onovc'%><br />

<%= link_to "Off Net OVC Inventory", :action => 'index_offovc'%><br />

app/views/admin/new_port.html.erb
<h1>New Port for <%= @node.name %> </h1>

<%= error_messages_for 'port' %>

<fieldset>
  <legend>Port Details</legend>
  <%= form_for :port, :url => { :action => 'save_port', :id => @node.id } do |f| %>
	<%= render :partial => 'input_port', :object => @port, :locals => {:f => f} %>			      
    <%= submit_tag "Save", :class => "submit" %>
  <% end %>
</fieldset>	

<%= link_to "Edit Node #{@node.name}", :action => 'edit_node', :id => @node.id %><br />